### ISSUE TITLE
make build fails

### ISSUE THREAD

**Issue by devarshishah3** [ciscoecosystem/terraform-provider-aci#11]
==> Checking that code complies with gofmt requirements...
go install
# github.com/ciscoecosystem/terraform-provider-aci/aci
aci/resource_aci_fvaepg.go:297:13: fvAEPgAttr.Annotation undefined (type models.ApplicationEPGAttributes has no field or method Annotation)
aci/resource_aci_fvaepg.go:300:13: fvAEPgAttr.ExceptionTag undefined (type models.ApplicationEPGAttributes has no field or method ExceptionTag)
aci/resource_aci_fvaepg.go:309:13: fvAEPgAttr.HasMcastSource undefined (type models.ApplicationEPGAttributes has no field or method HasMcastSource)
aci/resource_aci_fvaepg.go:330:13: fvAEPgAttr.Shutdown undefined (type models.ApplicationEPGAttributes has no field or method Shutdown)
aci/resource_aci_fvaepg.go:514:13: fvAEPgAttr.Annotation undefined (type models.ApplicationEPGAttributes has no field or method Annotation)
aci/resource_aci_fvaepg.go:517:13: fvAEPgAttr.ExceptionTag undefined (type models.ApplicationEPGAttributes has no field or method ExceptionTag)
aci/resource_aci_fvaepg.go:526:13: fvAEPgAttr.HasMcastSource undefined (type models.ApplicationEPGAttributes has no field or method HasMcastSource)
aci/resource_aci_fvaepg.go:547:13: fvAEPgAttr.Shutdown undefined (type models.ApplicationEPGAttributes has no field or method Shutdown)
aci/resource_aci_fvap.go:117:11: fvApAttr.Annotation undefined (type models.ApplicationProfileAttributes has no field or method Annotation)
aci/resource_aci_fvap.go:155:11: fvApAttr.Annotation undefined (type models.ApplicationProfileAttributes has no field or method Annotation)
aci/resource_aci_fvap.go:155:11: too many errors
make: *** [build] Error 2

**Comment by nkatarmal-crest** [comment]
Solved the issue can you please pull the changes from master branch and run the make build again.
