### ISSUE TITLE
Import not working properly

### ISSUE THREAD

**Issue by Trois-Six** [ciscoecosystem/terraform-provider-aci#15]
Hi,

I have a tenant named CDSTEST, it's a very simple tenant.

In vistore it has the following attributes 
* childAction: not set
* descr: not set
* extMngdBy: not set
* lcOwn: local
* modTs: 2017-06-14T07:53:48.083+01:00
* monPolDn: uni/tn-common/monepg-default
* name: CDSTEST
* nameAlias: not set
* ownerKey: not set
* ownerTag: not set
* status: not set  
* uid: 15374

If I import it, I get 

```
$ cat terraform.tfstate | jq -r ".modules[0].resources | map(select(.type == \"aci_tenant\"))"
[
  {
    "type": "aci_tenant",
    "depends_on": [],
    "primary": {
      "id": "uni/tn-CDSTEST",
      "attributes": {
        "annotation": "",
        "description": "",
        "id": "uni/tn-CDSTEST",
        "name_alias": ""
      },
      "meta": {
        "schema_version": "1"
      },
      "tainted": false
    },
    "deposed": [],
    "provider": "provider.aci"
  }
]
```
I think that at least the "name" attribute is missing ??

If I create a .tf file with 
```
resource "aci_tenant" "CDSTEST" {
  name = "CDSTEST"
}
```

terraform plan wants to destroy the resource:

```
-/+ aci_tenant.CDSTEST (new resource required)
      id:         "uni/tn-CDSTEST" => <computed> (forces new resource)
      annotation: "" => <computed>
      name:       "" => "CDSTEST" (forces new resource)
      name_alias: "" => <computed>
```

Regards,

Pierre

**Comment by nkatarmal-crest** [comment]
Can you please check now?

**Comment by Trois-Six** [comment]
yes !!
