### ISSUE TITLE
Add way to attach static ports to EPGs

### ISSUE THREAD

**Issue by Trois-Six** [ciscoecosystem/terraform-provider-aci#17]
Hi,

Let say I have a static port with the path "Pod-1/Node-88/eth1/1", i would like to be able to add it statically to an EPG. Could you create resources for that ?

Thank you,

Pierre

**Comment by nkatarmal-crest** [comment]
Can you please send an example for that?

**Comment by devarshishah3** [comment]
Pierre, You can use ACI rest for this ask. We have a limited number of data sources and resources we can upstream to Terraform. If you want, I  can send you the resource offline . But it will not be committed as a part of this branch at this point without further consultation with Hashicorp

**Comment by jgold** [comment]
Please may I see an example of how to create an aci_rest resource for generating an fvRsPathAtt, which I can then reference in the relation_fv_rs_path_att of my EGP resource?
Thanks,
Jonathon
