### ISSUE TITLE
Document how to use dep to resolve dependencies when building the provider

### ISSUE THREAD

**Issue by vfiftyfive** [ciscoecosystem/terraform-provider-aci#20]
I had multiple people reaching out because they didn't manage to resolve dependencies (new to Go).
There are 2 solutions: manually use ```go get``` or use ```dep```.
We should document how to use both in the README file.

Nic

**Comment by nkatarmal-crest** [comment]
Updated the readme with how to use dep to install all the dependencies. We are not going to use go-get as we have different branches for cloud-apic resources.
