### ISSUE TITLE
Bind Contracts to EPGs

### ISSUE THREAD

**Issue by wiwa1978** [ciscoecosystem/terraform-provider-aci#21]
We can create contracts using "aci_contract" and this will create a contract under a tenant. But then I want to associate this contract to two EPGs, one being a provider and the other being a consumer.

I'm using the following:

```
resource "aci_application_epg" "EPG_1" {
  application_profile_dn = "${aci_application_profile.AppProfile.id}"
  name                   = "EPG_1"
  description            = "This epg is created by terraform ACI providers"
  relation_fv_rs_prov    = ["${aci_contract.Contract_ICMP.id}"] 
}

resource "aci_application_epg" "EPG_2" {
  application_profile_dn = "${aci_application_profile.AppProfile.id}"
  name                   = "EPG_2"
  description            = "This epg is created by terraform ACI providers"
  relation_fv_rs_cons    = ["${aci_contract.Contract_ICMP.id}"] 
}

resource "aci_contract" "Contract_ICMP" {
  tenant_dn   = "${aci_tenant.Tenant.id}"
  name        = "Contract_ICMP"
  description = "This contract is created by terraform ACI provider"
  scope       = "context"
  target_dscp = "VA"
  prio        = "unspecified"
}
```
However this does not bind the contract to the EPG. 

Someone can provide help here?

**Comment by dpeachey** [comment]
Hi,

Use "name" instead of "id", like this:

    resource "aci_application_epg" "EPG_1" {
      application_profile_dn = "${aci_application_profile.AppProfile.id}"
      name                   = "EPG_1"
      description            = "This epg is created by terraform ACI providers"
      relation_fv_rs_prov    = ["${aci_contract.Contract_ICMP.name}"] 
    }

    resource "aci_application_epg" "EPG_2" {
      application_profile_dn = "${aci_application_profile.AppProfile.id}"
      name                   = "EPG_2"
      description            = "This epg is created by terraform ACI providers"
      relation_fv_rs_cons    = ["${aci_contract.Contract_ICMP.name}"] 
    }

Regards,

Dan

**Comment by wiwa1978** [comment]
Thanks. I confirm this is working.

Additional question: why is this called 'relation_fv_rs_cons' and not 'provider_contract' or something similar?

**Comment by dpeachey** [comment]
That's one for Cisco I guess :)

**Comment by devarshishah3** [comment]
@wiwa1978, this resource is generated based on the model objects. The object for provider contract is relation_fv_rs_cons.
