### ISSUE TITLE
unknown attribute 'annotation' in element 'fvAp'

### ISSUE THREAD

**Issue by MnrGreg** [ciscoecosystem/terraform-provider-aci#22]
Unable to apply annotations to ACI objects. Example below of failure when applying annotation "test" to EPG.

> aci_application_epg.aci_epg: Creating...
>   annotation:                       "" => "test"
>   application_profile_dn:           "" => "uni/tn-kubernetes_lab_tenant/ap-kubernetes_lab_ap"
>   description:                      "" => "Test EPG created directly with TF"
>   exception_tag:                    "" => "<computed>"
>   flood_on_encap:                   "" => "<computed>"
>   fwd_ctrl:                         "" => "<computed>"
>   has_mcast_source:                 "" => "<computed>"
> 15:25:56 [DEBUG] Error while reading relation vmmRsPrefEnhancedLagPol Invalid DN uni/uni/vmmp-Kubernetes/dom-kubernetes_vmm, wrong rn prefix uni at position 8
> 2019-04-01T15:25:56.042-0700 [DEBUG] plugin.terraform-provider-aci: 2019/04/01 15:25:56 Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 405 Not Allowed\r\nServer: nginx/1.10.3\r\nDate: Mon, 01 Apr 2019 22:25:20 GMT\r\nContent-Type: text/html\r\nContent-Length: 331\r\nConnection: close\r\nETag: \"5ad94ecd-14b\"\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<title>Untitled Document</title>\n</head>\n\n<body>\n405 Method Not Allowed\n</body>\n</html>\n"; err=<nil>
> 2019-04-01T15:25:56.049-0700 [DEBUG] plugin.terraform-provider-aci: 2019/04/01 15:25:56 [DEBUG] Error while reading relation infraRsVlanNs Invalid DN uni/uni/vmmp-Kubernetes/dom-kubernetes_vmm, wrong rn prefix uni at position 8
> 2019-04-01T15:25:56.049-0700 [DEBUG] plugin.terraform-provider-aci: 2019/04/01 15:25:56 [DEBUG] Error while reading relation vmmRsDomMcastAddrNs invalid character '<' looking for beginning of value
> 2019-04-01T15:25:56.056-0700 [DEBUG] plugin.terraform-provider-aci: 2019/04/01 15:25:56 [DEBUG] Error while reading relation vmmRsDefaultCdpIfPol Invalid DN uni/uni/vmmp-Kubernetes/dom-kubernetes_vmm, wrong rn prefix uni at position 8
> 2019-04-01T15:25:56.056-0700 [DEBUG] plugin.terraform-provider-aci: 2019/04/01 15:25:56 [DEBUG] Error while reading relation vmmRsDefaultLacpLagPol invalid character '<' looking for beginning of value
> 2019-04-01T15:25:56.063-0700 [DEBUG] plugin.terraform-provider-aci: 2019/04/01 15:25:56 [DEBUG] Error while reading relation infraRsVlanNsDef Invalid DN uni/uni/vmmp-Kubernetes/dom-kubernetes_vmm, wrong rn prefix uni at position 8
> 2019-04-01T15:25:56.063-0700 [DEBUG] plugin.terraform-provider-aci: 2019/04/01 15:25:  is_attr_based_e_pg:               "" => "<computed>"
>   match_t:                          "" => "<computed>"
> 56 Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 405 Not Allowed\r\nServer: nginx/1.10.3\r\nDate: Mon, 01 Apr 2019 22:25:20 GMT\r\nContent-Type: text/html\r\nContent-Length: 331\r\nConnection: close\r\nETag: \"5ad94ecd-14b\"\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n<title>Untitled Document</title>\n</head>\n\n<body>\n405 Method Not Allowed\n</body>\n</html>\n"; err=<nil>
> 2019-04-01T15:25:56.071-0700 [DEBUG] plugin.terraform-provider-aci: 2019/04/01 15:25:56 [DEBUG] Error while reading relation infraRsVipAddrNs Invalid DN uni/uni/vmmp-Kubernetes/dom-kubernetes_vmm, wrong rn prefix uni at position 8
> 2019-04-01T15:25:56.071-0700 [DEBUG] plugin.terraform-provider-aci: 2019/04/01 15:25:56 [DEBUG] Error while reading relation vmmRsDefaultLldpIfPol invalid character '<' looking for beginning of value
> 2019-04-01T15:25:56.078-0700 [DEBUG] plugin.terraform-provider-aci: 2019/04/01 15:25:56 [DEBUG] Error while reading relation vmmRsDefaultStpIfPol Invalid DN uni/uni/vmmp-Kubernetes/dom-kubernetes_vmm, wrong rn prefix uni at position 8
> 2019-04-01T15:25:56.078-0700 [DEBUG] plugin.terraform-provider-aci: 2019/04/01 15:25:56 [DEBUG] Error while reading relation infraRsDomVxlanNsDef invalid character '<' looking for beginning of value
> 2019-04-01T15:25:56.085-0700 [DEBUG] plugin.terraform-provider-aci: 2019/04/01 15:25:56 [DEBUG] Error while reading relation vmmRsDefaultFwPol Invalid DN uni/uni/vmmp-Kubernetes/dom-kubernetes_vmm, wrong rn prefix uni at position 8
> 2019-04-01T15:25:56.085-0700 [DEBUG] plugin.terraform-provider-aci: 2019/04/01 15:25:56 [DEBUG] Error while reading relation vmmRsDefaultL2InstPol invalid character '<' looking for beginning of value
> 2019/04/01 15:25:56 [TRACE] root: eval: *terraform.EvalWriteState
> 2019/04/01 15:25:56 [TRACE] root: eval: *terraform.EvalAppl  name:                             "" => "kubernetes_lab_epg"
>   name_alias:                       "" => "<computed>"
>   pc_enf_pref:                      "" => "<computed>"
>   pref_gr_memb:                     "" => "<computed>"
>   prio:                             "" => "<computed>"
>   relation_fv_rs_dom_att.#:         "" => "1"
>   relation_fv_rs_dom_att.696330721: "" => "uni/vmmp-Kubernetes/dom-kubernetes_vmm"
>   shutdown:                         "" => "<computed>"
> 2019/04/01 15:25:56 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:
> 
> * aci_application_epg.aci_epg: unknown attribute 'annotation' in element 'fvAEPg'
> 2019/04/01 15:25:56 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:
> 
> * aci_application_epg.aci_epg: unknown attribute 'annotation' in element 'fvAEPg'
> 
> 2019/04/01 15:25:56 [DEBUG] plugin: waiting for all plugin processes to complete...
> Error: Error applying plan:
> 
> 1 error(s) occurred:
> 
> * aci_application_epg.aci_epg: 1 error(s) occurred:
> 
> * aci_application_epg.aci_epg: unknown attribute 'annotation' in element 'fvAEPg'
> 
> Terraform does not automatically rollback in the face of errors.
> 2019-04-01T15:25:56.119-0700 [DEBUG] plugin.terraform-provider-aci: 2019/04/01 15:25:56 [ERR] plugin: plugin server: accept unix /var/folders/bv/936vd8y14s97g6fzgn8s0tbdgd4cvd/T/plugin154366668: use of closed network connection
> Instead, your Terraform state file has been partially updated with
> any resources that successfully completed. Please address the error
> above and apply again to incrementally change your infrastructure.
> 
> 
> 2019-04-01T15:25:56.121-0700 [DEBUG] plugin: plugin process exited: path=/Users/gmay/.terraform.d/plugins/terraform-provider-aci

**Comment by nkatarmal-crest** [comment]
Hello, @MnrGreg

 I am not able to reproduce this issue on my APIC setup. It seems this issue is because of the older code. Can you please pull the latest changes from the master branch and try building your provider again. After that try re-running the terraform again.

Thanks,
Nirav.

**Comment by MnrGreg** [comment]
Hi @nkatarmal-crest 

My goal is to add tags to EPG's. Tags as in the `/api/tag/`. Are these annotation attributes tags or something else?

I've rebased from master but still getting the same result. This time I've simplified a bit by just adding an annotation to the existing Tenant object.


```
$ terraform plan -parallelism=1
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

aci_tenant.kubernetes_lab_tenant: Refreshing state... (ID: uni/tn-kubernetes_lab_tenant)
aci_application_profile.kubernetes_app_profile: Refreshing state... (ID: uni/tn-kubernetes_lab_tenant/ap-kubernetes_lab_ap)

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place
  - destroy

Terraform will perform the following actions:

  - aci_application_profile.kubernetes_app_profile

  ~ aci_tenant.kubernetes_lab_tenant
      annotation: "" => "testing-annotation"


Plan: 0 to add, 1 to change, 1 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

$ terraform apply -auto-approve -parallelism=1
aci_tenant.kubernetes_lab_tenant: Refreshing state... (ID: uni/tn-kubernetes_lab_tenant)
aci_application_profile.kubernetes_app_profile: Refreshing state... (ID: uni/tn-kubernetes_lab_tenant/ap-kubernetes_lab_ap)
aci_application_profile.kubernetes_app_profile: Destroying... (ID: uni/tn-kubernetes_lab_tenant/ap-kubernetes_lab_ap)
aci_application_profile.kubernetes_app_profile: Destruction complete after 0s
aci_tenant.kubernetes_lab_tenant: Modifying... (ID: uni/tn-kubernetes_lab_tenant)
  annotation: "" => "testing-annotation"

Error: Error applying plan:

1 error(s) occurred:

* aci_tenant.kubernetes_lab_tenant: 1 error(s) occurred:

* aci_tenant.kubernetes_lab_tenant: unknown attribute 'annotation' in element 'fvTenant'

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Application Policy Infrastructure Controller Version: 3.1(2o)

$ terraform version
Terraform v0.11.13
+ provider.aci (unversioned)

**Comment by nkatarmal-crest** [comment]
No they are not tags. I think your ACI version is not supporting the annotation. This Provider is tested against the ACI version 4.0 and above.
