### ISSUE TITLE
Request: add modules/functions to be able to provision fabric side of ACI

### ISSUE THREAD

**Issue by JockeW-DvL** [ciscoecosystem/terraform-provider-aci#23]
Right now we can do most of what is needed under Tenant, but i also would like to be able to provision under fabric -> Access Policies, such as:
 * add EPG to vlan mapping under AAEP
 * create new AAEPs
 * create new Interface Policy Groups
 * add port bindings to  Interface Select Profiles
 * etc

Is this something that can be added?

**Comment by devarshishah3** [comment]
@JockeW-DvL , yes.

**Comment by nkatarmal-crest** [comment]
@JockeW-DvL  I have added support for fabric resources to the provider for policy groups, lsservers etc.

**Comment by JockeW-DvL** [comment]
thanks for the updated provider, it's great but i'm still missing a couple of things, for example:

* add interface selectors to to Leaf interface profile
* ability to add AAEPs
* ability to add EPG to Vlan mapping in AAEP or example of how to add static ports to EPG

**Comment by nkatarmal-crest** [comment]
@JockeW-DvL I have added required resources.
