### ISSUE TITLE
Make build issue

### ISSUE THREAD

**Issue by karmicgeezer** [ciscoecosystem/terraform-provider-aci#24]
When running 'make build' I'm getting the following errors:

go install
# github.com/ciscoecosystem/terraform-provider-aci/aci
aci/resource_aci_fcifpol.go:88:69: undefined: models.InterfaceFCPolicy
aci/resource_aci_fcifpol.go:103:46: undefined: models.InterfaceFCPolicy
aci/resource_aci_fvepretpol.go:92:75: undefined: models.EndPointRetentionPolicy
aci/resource_aci_fvepretpol.go:107:55: undefined: models.EndPointRetentionPolicy
aci/resource_aci_infraaccbndlgrp.go:219:77: undefined: models.PCVPCInterfacePolicyGroup
aci/resource_aci_infraaccbndlgrp.go:234:62: undefined: models.PCVPCInterfacePolicyGroup
aci/resource_aci_infraaccportgrp.go:211:77: undefined: models.LeafAccessPortPolicyGroup
aci/resource_aci_infraaccportgrp.go:226:62: undefined: models.LeafAccessPortPolicyGroup
aci/resource_aci_infraaccportp.go:46:72: undefined: models.LeafInterfaceProfile
aci/resource_aci_infraaccportp.go:61:55: undefined: models.LeafInterfaceProfile
aci/resource_aci_infraaccportp.go:61:55: too many errors
make: *** [build] Error 2

Versions:
go version go1.12.4 darwin/amd64
Terraform v0.11.13

**Comment by JockeW-DvL** [comment]
you probably need to update the ciscoecosystem/aci-go-client i did and i can compile the terraform provider

**Comment by karmicgeezer** [comment]
Probably me missing something

go get github.com/ciscoecosystem/aci-go-client - all good
cd $GOPATH/src/github.com/ciscoecosystem/terraform-provider-aci
dep ensure
make build

Same errors.

Many thanks for responding, much appreciated.

**Comment by JockeW-DvL** [comment]
Make sure you have the aci-go-client installed in $GOPATH/src/github.com/ciscoecosystem/aci-go-client, thats all i've done.

**Comment by karmicgeezer** [comment]
Yep, it's there:

$ ~/go/src/github.com/ciscoecosystem/aci-go-client
ls
Gopkg.lock LICENSE    client     doc.go     tests
Gopkg.toml README.md  container  models

**Comment by karmicgeezer** [comment]
Is there anything else worth trying to get the project to build?

**Comment by JockeW-DvL** [comment]
for ACI If you is satisfied with building networking stuff:

- Tenants
- EPG
- BD
- Contracts
- etc
i think so.

As you have seen in my other issues there are some issues with using terraform for ACI, but i believe it is worth it because when the provider is working properly it will be really good.

**Comment by karmicgeezer** [comment]
Sorry, I badly worded the last message. I'm not able to build the project.

Despite having aci-go-client, 'dep ensure' runs with no issue, but make build gives:

 make build
==> Checking that code complies with gofmt requirements...
go install
# github.com/ciscoecosystem/terraform-provider-aci/aci
aci/resource_aci_fcifpol.go:88:69: undefined: models.InterfaceFCPolicy
aci/resource_aci_fcifpol.go:103:46: undefined: models.InterfaceFCPolicy
aci/resource_aci_fvepretpol.go:92:75: undefined: models.EndPointRetentionPolicy
aci/resource_aci_fvepretpol.go:107:55: undefined: models.EndPointRetentionPolicy
aci/resource_aci_infraaccbndlgrp.go:219:77: undefined: models.PCVPCInterfacePolicyGroup
aci/resource_aci_infraaccbndlgrp.go:234:62: undefined: models.PCVPCInterfacePolicyGroup
aci/resource_aci_infraaccportgrp.go:211:77: undefined: models.LeafAccessPortPolicyGroup
aci/resource_aci_infraaccportgrp.go:226:62: undefined: models.LeafAccessPortPolicyGroup
aci/resource_aci_infraaccportp.go:46:72: undefined: models.LeafInterfaceProfile
aci/resource_aci_infraaccportp.go:61:55: undefined: models.LeafInterfaceProfile
aci/resource_aci_infraaccportp.go:61:55: too many errors
make: *** [build] Error 2

**Comment by JockeW-DvL** [comment]
Aah, OK.

to me it looks like you don't have the latest version of aci-go-client

go to (in cmd or terminal or whatever you are using) ~/go/src/github.com/ciscoecosystem/aci-go-client and  perform a git pull and try again to build the ACI provider. this helped for me. Seems that aci-go-client is uppdated at the same time as the transform provider is.

**Comment by karmicgeezer** [comment]
The aci-go-client was pulled the same time as the terraform-provider-aci:

$ git pull
-> Already up to date.

**Comment by JockeW-DvL** [comment]
Sorry then i can't help you

**Comment by karmicgeezer** [comment]
No worries, thanks for trying.
