### ISSUE TITLE
Provider Review

### ISSUE THREAD

**Issue by bill-rich** [ciscoecosystem/terraform-provider-aci#25]
Hello! 

My name is Bill, I'm a member of the Terraform team @ HashiCorp.

I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking remaining items and discussion. The review was done on the git commit  3fd2e74e6d4489e06abb9787f52484335db77c46.

- [x] It looks like the descriptions in the schema were auto generated, but many were not defined. In those cases, please remove the descriptions.
- [x] Resources that support Import don't have corresponding import tests. You can add the below as the last test step to all resource tests that support import. 
```
{
	ResourceName:            resourceName,
	ImportState:             true,
	ImportStateVerify:       true,
},
```
- [x] Acceptance tests should check that all arguments and attributes are correctly set and read.
- [x] Not a big deal, but we typically order our imports with stdlib ones first, then whitespace, then the rest (`goimports` can help with this)
- [x] All arguments and attributes should be set in the read function. That way if anything changes, those changes will be reflected in the state. The `relation_*` arguments do not seem to be set during read.
- [x] In the create and update functions for resource_aci_fvaepg.go, it looks like multiple API calls are being made to create the resource. If that is the case, the resource should be put into partial mode while calls are being made so that if an error occurs, the resource can still be managed. This can be done using set.Partial()
- [x] Each CRUD function should include at least two log messages to describe which resource is being worked on and when the function begins and ends successfully. For example, see [here](https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/vsphere/resource_vsphere_compute_cluster.go#L537-L572)
- [x] Resources that support updating should include an update test in the acceptance tests.
- [x] Seems to be overriding what is set in resource schema for `name` and `description`. This is confusing because what is shown in the resource schema for `name` is not what is actually being used.
- [x] A lot of the data sources seem to be unnecessary since they have required arguments and no computed attributes. The data sources that are not reading anything new should be removed.
- [x] Resource docs should be in `website/docs/r` rather than `website/docs/resources`
- [x] If any data sources are going to be left in, they should have documentation.
- [x] Resource docs should not include the `resource_aci_` prefix in the name. E.g `fcifpol.html.markdown` instead of `resource_aci_fcifpol.html.markdown`
- [x] Resource docs should include separate `Argument` and `Attribute` sections. See https://github.com/terraform-providers/terraform-provider-vsphere/blob/master/website/docs/r/folder.html.markdown for an example
- [x] Resources that support importing should include documentation on importing.
- [x] All arguments and attributes should have a description in documentation.
- [x] Examples in documentation should be run through `terraform fmt`
- [x] Examples in documentation should include more details beyond just “example” for each argument, should include at least simple examples of resources or data sources the example depends on.
- [x] Documentation should include more information about arguments and how to use it. It should also make it as clear as possible what the requirements and constraints are. Eg describing what `pref_gr_memb` is rather than just saying it is the `pref_gr_memb` of an object, or describing how `relation_vz_rs_any_to_prov` can be used in an n:m way rather than just listing “Cardinality - N_TO_M”

**Comment by devarshishah3** [comment]
@bill-rich : Regarding "Examples in documentation should include more details beyond just “example” for each argument, should include at least simple examples of resources or data sources the example depends on." Do you want us to have examples for all resources and datatypes in the examples dir ?

**Comment by cgriggs01** [comment]
> @bill-rich : Regarding "Examples in documentation should include more details beyond just “example” for each argument, should include at least simple examples of resources or data sources the example depends on." Do you want us to have examples for all resources and datatypes in the examples dir ?

I believe this is in regard to having an implementation example for each resource or datasource on the website documentation pages.

**Comment by bill-rich** [comment]
The changes in the `review` branch look good! It looks like you've got all the issues we discussed covered. The only other item I'd recommend is creating some acceptance tests for the data source. I don't think it is required to move forward since it looks like the data sources are mostly just looking up the resource and then reading in the attributes using the same functions as the resources, but it would still be a good idea to add at some point just to ensure resource lookups are working and that future changes on the resource side don't break the data sources.

**Comment by nkatarmal-crest** [comment]
Thanks, Bill, I will add the required acceptance tests to the provider.
