### ISSUE TITLE
Issue with aci_access_port_selector

### ISSUE THREAD

**Issue by Trois-Six** [ciscoecosystem/terraform-provider-aci#30]
Hi,

I declare an access_port_selector resource as:

```
resource "aci_access_port_selector" "LIP_MYLEAF100_Eth1_10" {
  name                           = "Eth1.10"
  access_port_selector_type      = "range"
  leaf_interface_profile_dn      = "${aci_leaf_interface_profile.LIP_MYLEAF100.id}"
  relation_infra_rs_acc_base_grp = "${aci_pcvpc_interface_policy_group.LPG_MYLPG001.id}"
}
```
When I import it from my fabric, I get:

```
$ terraform state show aci_access_port_selector.LIP_MYLEAF100_Eth1_10
id                        = uni/infra/accportprof-LIP_MYLEAF100/hports-Eth1.10-typ-range
access_port_selector_type = range
annotation                = 
description               = 
leaf_interface_profile_dn = uni/infra/accportprof-LIP_MYLEAF100
name                      = Eth1.10-typ-range
name_alias                = 
```

whereas, the real name of the interface is Eth1.10. If after the import I try to apply, Terraform wants to destroy/create back the resource.

Terraform version: v0.11.11
ACI Provider version: git20190513.fde7cea

Can you look at it ?

Regards,

Pierre

**Comment by nkatarmal-crest** [comment]
This issue has been addressed. I will release new code soon to fix this issue.

**Comment by devarshishah3** [comment]
Fixed in review branch. This will be merged with master once the changes have been approved by Hashicorp
