### ISSUE TITLE
Issue with aci_subnet

### ISSUE THREAD

**Issue by Trois-Six** [ciscoecosystem/terraform-provider-aci#31]
Hi,

The object fvSubnet has got an empty "name" attribute, as you can see in the generated code in https://github.com/ciscoecosystem/terraform-provider-aci/blob/master/aci/resource_aci_fvsubnet.go. or in a download from an APIC:

```
$ cat subnet-\[10.10.1.254_24\].json | jq .
{
  "totalCount": "1",
  "imdata": [
    {
      "fvSubnet": {
        "attributes": {
          "ctrl": "nd",
          "descr": "",
          "dn": "uni/tn-MYTN/BD-BD_1/subnet-[10.10.1.254/24]",
          "ip": "10.10.1.254/24",
          "name": "",
          "nameAlias": "",
          "preferred": "no",
          "scope": "public",
          "virtual": "no"
        }
      }
    }
  ]
}
```
but if you don't set a name in the Terraform resource definition, you get an error:
```
Error: aci_subnet.subnet_1: "name": required field is not set
```
If you set a name attribute (other than en empty string: ""), the object is always destroyed and re-created at every run:
```
aci_subnet.subnet_1: Refreshing state... (ID: uni/tn-MYTN/BD-BD_1/subnet-[10.10.1.254/24])
aci_subnet.subnet_1: Destroying... (ID: uni/tn-MYTN/BD-BD_1/subnet-[10.10.1.254/24])
aci_subnet.subnet_1: Destruction complete after 0s
aci_subnet.subnet_1: Creating...
  annotation:       "" => "<computed>"
  bridge_domain_dn: "" => "uni/tn-MYTN/BD-BD_1"
  ctrl:             "" => "nd"
  ip:               "" => "10.10.1.254/24"
  name:             "" => "subnet_1"
  name_alias:       "" => "<computed>"
  preferred:        "" => "no"
  scope:            "" => "public"
  virtual:          "" => "no"
aci_subnet.subnet_1: Creation complete after 0s (ID: uni/tn-MYTN/BD-BD_1/subnet-[10.10.1.254/24])
```
The only way to get it working is defining a resource with an empty name:
```
resource "aci_subnet" "subnet_1" {
  name             = ""
  bridge_domain_dn = "${aci_bridge_domain.bd_1.id}"
  ip               = "10.10.1.254/24"
  ctrl             = "nd"
  preferred        = "no"
  scope            = "public"
  virtual          = "no"
}
```
I think that for this resource, the name attribute should not be used.

Terraform version: v0.11.11
ACI provider version: git20190513.fde7cea

Regards,

Pierre

**Comment by nkatarmal-crest** [comment]
Yes, this attribute will be removed in the upcoming version of the provider. I will be pushing the changes soon. That will solve your issue.

**Comment by nkatarmal-crest** [comment]
This issue has been fixed and changes are pushed in the review branch of the provider as well as the client.
