### ISSUE TITLE
Parallelism != 1

### ISSUE THREAD

**Issue by Trois-Six** [ciscoecosystem/terraform-provider-aci#32]
Hi,

The problem of parallelism different from 1 is not solved.
If I run a plane with a parallelism = 1, terraform sees no change, if I do the same thing without disabling parallelism, the result is not at all the same.
I can send you traces, but in private.

Terraform version: 0.11.14
ACI provider version: git20190522.f5233ba

Pierre

**Comment by devarshishah3** [comment]
@Trois-Six , can you send me the traces on my cisco email

**Comment by Trois-Six** [comment]
I just sent an email to you with the traces and tf files.

**Comment by nkatarmal-crest** [comment]
Hey,

The issue with parallelism is from ACI side, ACI limits the no. of requests from a machine to some threshold to avoid DOS attack. So if you use parallelism with more than one threads then terraform will be making a lot of API requests in a very small time period, So ACI blocks your requests and that makes Terraform behave unexpectedly.  

Nirav.

**Comment by vfiftyfive** [comment]
The problem should not happen when certificate based authentication is used (like with our Ansible module). But apparently it is not the case, this needs investigation.

Nic

**Comment by nkatarmal-crest** [comment]
@vfiftyfive  Can you please pull the latest changes from the aci-go-client and the provider on the **review** branch and try running your terraform configuration files again?

Nirav.
