### ISSUE TITLE
Hanging Sessions

### ISSUE THREAD

**Issue by arian-saliu** [ciscoecosystem/terraform-provider-aci#39]
@nkatarmal-crest

Hi There. We are experiencing some issues with our Cisco ACI.
Basically when we try to apply more than 10 resources using certificate authentication and with disabled throttling on Cisco ACI, also using parellelism=1 the terraform code runs forever.

For all of our resources we are using counts and at a certain point when more than 10 resources are being created the whole process starts running forever.

Our ACI version is 3.2.5

We are running the latest terraform version (as of the time of writing) which is 12.4

I tried building the provider from the review branch as well... but that didn't help either.

Please assist with that.

**Comment by Akshat0694** [comment]
Same issue!

**Comment by nkatarmal-crest** [comment]
@arian-saliu @Akshat0694 I will look into it.
