### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by dpeachey** [ciscoecosystem/terraform-provider-aci#4]
Hi,

I often get this error when running terraform plan or apply:

```
Error: Error refreshing state: 2 error(s) occurred:

* aci_subnet.dp-eval-subnet: 1 error(s) occurred:

* aci_subnet.dp-eval-subnet: aci_subnet.dp-eval-subnet: invalid character '<' looking for beginning of value
* aci_subnet.dp-eval-subnet-v6: 1 error(s) occurred:

* aci_subnet.dp-eval-subnet-v6: aci_subnet.dp-eval-subnet-v6: invalid character '<' looking for beginning of value
```

It is transient, and if I re-run the command it usually disappears. It also is not always the same resources that the error occurs with.

Thanks,

Dan

**Comment by nkatarmal-crest** [comment]
That issue is because of request throttling present in the ACI. If you use signature-based authentication than you will not face this error.

**Comment by devarshishah3** [comment]
I've notice I've got randomly runtime error upon running terraform apply
invalid character '<' looking for beginning of value
then if I run the command again it's fine
**This may be due to some unicode formating in the plugin code**

Using cert based auth already

**Comment by dpeachey** [comment]
Hi,

I'm having much better results using the '-parallelism=1' argument when running a plan or apply. I do not get this message anymore.

Regards,

Dan

**Comment by vfiftyfive** [comment]
solved with "parallelism" option
