### ISSUE TITLE
fvAEPg resource relations

### ISSUE THREAD

**Issue by jgcasd** [ciscoecosystem/terraform-provider-aci#42]
Do you have any examples of how to override the default parameters when specifying relations?

For example, the resource "aci_application_epg" specifies it allows relation arguments for: 

relation_fv_rs_path_att 

This looks like it only accepts a string. How do I pass in the VLAN, trunking mode, deployment immediacy, etc?

Same for something like:

relation_fv_rs_dom_att 

I have a need to specify "pre-provision" on the resolution immediacy for vmm domains. How do I do so?

**Comment by devarshishah3** [comment]
right now the provider just builds teh relationship to the domain. One way of specifying the resoultion immediacy and other parameters is to use aci_rest.
It would be on the lines of:

resource "aci_rest" "epgdomainrelationattr" {
  path       = "uni/tn-99_Customer01/ap-app-test/epg-kafka-epg/rsdomAtt-[uni/vmmp-VMware/dom-test2].json"
  class_name = "fvRsDomAtt"

  content = {
    "dn"   = "uni/tn-99_Customer01/ap-app-test/epg-kafka-epg/rsdomAtt-[uni/vmmp-VMware/dom-test2]"
    "name" = "tntest"
    "forceResolve": "yes"
    "instrImedcy": "lazy"
    "lagPolicyName": ""
  }
}

**Comment by waseem-h** [comment]
I've tried creating the relation between vmm_domain and EPG using the aci_rest resource. It works fine on the 1st apply. But when I do a terraform deploy again, it modifies the EPG and the vmm_domain connection gets removed. I've also tried specifying a relation in the EPG alongwith the aci_rest resource for updating, but the aci_rest call fails saying that the vmm_domain already exists

```
resource "aci_application_epg" "epg" {
  application_profile_dn = var.application_profile_id
  name                   = var.name

  relation_fv_rs_bd   = module.bridge_domain.bridge_domain_name
  relation_fv_rs_cons = var.consumed_contracts
  relation_fv_rs_prov = var.provided_contracts
  #relation_fv_rs_dom_att = [data.aci_vmm_domain.vmm_domain.id]
}

data "aci_vmm_domain" "vmm_domain" {
  provider_profile_dn = "uni/vmmp-VMware"
  name                = var.vmm_domain
}

resource "aci_rest" "fix_vmm_domain" {
  path       = "api/node/mo.json"
  class_name = "fvRsDomAtt"
  content = {
    switchingMode = "AVE"
    encapMode     = "vlan"
    instrImedcy   = "immediate"
    resImedcy     = "immediate"
    status = "modified"
    dn = "${aci_application_epg.epg.id}/rsdomAtt-[${data.aci_vmm_domain.vmm_domain.id}]"
  }

  depends_on = [aci_application_epg.epg]
}
```

Is there a proper way of doing this? Our pipelines run terraform apply all the time and the if the vmm_Domain link break during the apply, all our VM's need to be restarted which is not acceptable. The state should always be consistent. Maybe the aci_application_epg resource should respect the aci_rest resource links. What do you think @devarshishah3 @nkatarmal-crest ?
