### ISSUE TITLE
aci_filter erroneous modifications

### ISSUE THREAD

**Issue by jgcasd** [ciscoecosystem/terraform-provider-aci#43]
Whenever I run terraform apply for the aci_filter resources it keeps trying to modify these 2 parameters:

aci_filter.udp_123: Modifying... (ID: uni/tn-tf_test/flt-udp_123)
  relation_vz_rs_fwd_r_flt_p_att: "{}" => ""
  relation_vz_rs_rev_r_flt_p_att: "{}" => ""

Here is the content of my resource, I'm not specifying those parameters at all:
```
resource "aci_filter" "udp_123" {
  tenant_dn   = "${aci_tenant.test.id}"
  description = "${var.default_description}"
  name        = "udp_123"
}
```

root@ece0b58da847:~# terraform --version
Terraform v0.11.14

Your version of Terraform is out of date! The latest version
is 0.12.5. You can update by downloading from www.terraform.io/downloads.html

**Comment by nkatarmal-crest** [comment]
This issue has been fixed. Please pull the changes from review branch.
