### ISSUE TITLE
remote error: tls: handshake failure on ACI version 4.2(x) not on ACI version 3.2(x)

### ISSUE THREAD

**Issue by JockeW-DvL** [ciscoecosystem/terraform-provider-aci#52]
I'm using terraform version v0.12.19 and ACI provider version v0.1.4 and certificate to authenticate. i'm getting the same issues on both MacOS Catalina and Ubuntu 19.10.

I'm getting the following errors when trying to provision in ACI ver 4.2(x).
"Error: Post https://172.27.50.242/api/node/mo.json: remote error: tls: handshake failure

  on tenant.tf line 1, in resource "aci_tenant" "Test":
   1: resource "aci_tenant" "Test" {

"

But when i'm provision in ACI 3.2(x) it is working perfectly.

The config files are as follows:
[app.tf.txt](https://github.com/ciscoecosystem/terraform-provider-aci/files/4097497/app.tf.txt)
[bd.tf.txt](https://github.com/ciscoecosystem/terraform-provider-aci/files/4097499/bd.tf.txt)
[epg.tf.txt](https://github.com/ciscoecosystem/terraform-provider-aci/files/4097500/epg.tf.txt)
[main.tf.txt](https://github.com/ciscoecosystem/terraform-provider-aci/files/4097501/main.tf.txt)
[ports.tf.txt](https://github.com/ciscoecosystem/terraform-provider-aci/files/4097502/ports.tf.txt)
[tenant.tf.txt](https://github.com/ciscoecosystem/terraform-provider-aci/files/4097503/tenant.tf.txt)

**Comment by devarshishah3** [comment]
There are TLS changes in the new release of the ACI, which is causing the TLS failure. I have updated the provider to use new cipher suites, this error should be resolved now.

**Comment by JockeW-DvL** [comment]
Thanks @devarshishah3 , i have now verified this and it works perfectly.
