### ISSUE TITLE
Examples need to be updated with specific examples

### ISSUE THREAD

**Issue by devarshishah3** [ciscoecosystem/terraform-provider-aci#6]
Relation exmaples have test in the data. Please provide an example with the right dn.id
Applicable to all providers

one of the examples is in aci_epg

  relation_fv_rs_bd            = "testbd_update"
  relation_fv_rs_dom_att       = ["test"]                                            # Relation to infraDomP class. Cardinality - N_TO_M.
  relation_fv_rs_fc_path_att   = ["testfabric"]                                      # Relation to fabricPathEp class. Cardinality - N_TO_M.
  relation_fv_rs_prov          = ["testcontract"]                                    # Relation to vzBrCP class. Cardinality - N_TO_M.
  relation_fv_rs_cons_if       = ["testconsif"]                                      # Relation to vzCPIf class. Cardinality - N_TO_M.
  relation_fv_rs_sec_inherited = ["testinherited"]                                   # Relation to fvEPg class. Cardinality - N_TO_M.
  relation_fv_rs_node_att      = ["testnodeatt"]                                     # Relation to fabricNode class. Cardinality - N_TO_M.
  relation_fv_rs_dpp_pol       = "testdpppol"                                        # Relation to qosDppPol class. Cardinality - N_TO_ONE.
  relation_fv_rs_cons          = ["testrscons"]                                      # Relation to vzBrCP class. Cardinality - N_TO_M.
  relation_fv_rs_trust_ctrl    = "testtrustctrl"                                     # Relation to fhsTrustCtrlPol class. Cardinality - N_TO_ONE.
  relation_fv_rs_path_att      = ["testpathatt"]                                     # Relation to fabricPathEp class. Cardinality - N_TO_M.
  relation_fv_rs_prot_by       = ["testprot"]                                        # Relation to vzTaboo class. Cardinality - N_TO_M.
  relation_fv_rs_ae_pg_mon_pol = "aepgmonpol"                                        # Relation to monEPGPol class. Cardinality - N_TO_ONE.
  relation_fv_rs_intra_epg     = ["testintraepg"]                                    # Relation to vzBrCP class. Cardinality - N_TO_M.

**Comment by nkatarmal-crest** [comment]
Hello Devarshi,

I have updated the examples with respective dn id.

Nirav.

**Comment by devarshishah3** [comment]
Nirav,
All the examples and all the fields need to be updated

**Comment by nkatarmal-crest** [comment]
I have updated the examples fields with all the resources we are supporting currently. Rest of the relations field contains the Model objects that are currently being not supported by the provider.
